-- liquibase formatted sql

-- changeset benriley:1760704772848-1 splitStatements:false
CREATE TABLE "logs" ("customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "first_name" VARCHAR(50), "last_name" VARCHAR(50), "email" VARCHAR(100), "phone_number" VARCHAR(20), "qa_flagged" BOOLEAN DEFAULT FALSE, CONSTRAINT "logs_pkey" PRIMARY KEY ("customer_id"));

-- changeset benriley:1760704772848-2 splitStatements:false
CREATE TABLE "chat" ("customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "first_name" VARCHAR(50), "last_name" VARCHAR(50), "email" VARCHAR(100), "phone_number" VARCHAR(20), "qa_flagged" BOOLEAN DEFAULT FALSE, CONSTRAINT "chat_pkey" PRIMARY KEY ("customer_id"));

-- changeset benriley:1760704772848-3 splitStatements:false
CREATE TABLE "files" ("customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "first_name" VARCHAR(50), "last_name" VARCHAR(50), "email" VARCHAR(100), "phone_number" VARCHAR(20), "qa_flagged" BOOLEAN DEFAULT FALSE, CONSTRAINT "files_pkey" PRIMARY KEY ("customer_id"));

-- changeset benriley:1760704772848-4 splitStatements:false
ALTER TABLE "customers" ADD "qa_flagged" BOOLEAN DEFAULT FALSE;

