# diff-flow.flowfile.yaml
# Generates a diff-changelog (DEV → TEST) and applies it to TEST.

globalVariables:
  # Where to write the diff changelog
  DIFF_CHANGELOG: "${DIFF_CHANGELOG:-out/diff-changelog.sql}"

  # Which object types to include (adjust as you like)
  DIFF_TYPES: "${DIFF_TYPES:-tables,views,columns,primaryKeys,uniqueConstraints,indexes,foreignKeys,sequences,checkConstraints}"

stages:
  Default:
    actions:
      # 1) Create a changeset file that captures diffs between DEV (reference) and TEST (target)
      - type: liquibase
        command: diff-changelog
        cmdArgs:
          changelog-file: "${DIFF_CHANGELOG}"     # output file
          format: sql                              # SQL-formatted changelog (your ask)
          reference-url: "${DEV_URL}"              # DEV = reference
          reference-username: "${LB_USER}"
          reference-password: "${LB_PWD}"
          url: "${TEST_URL}"                       # TEST = target
          username: "${LB_USER}"
          password: "${LB_PWD}"
          diff-types: "${DIFF_TYPES}"

      # 2) Apply that diff to TEST
      - type: liquibase
        command: update
        cmdArgs:
          changelog-file: "${DIFF_CHANGELOG}"
          url: "${TEST_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"
