# Flow: snapshot → update → diff (diffs against the pre-snapshot)
# Values are injected via env vars by the GitHub workflow:
#   DB_URL, CONTEXTS, SNAPSHOT, DIFF, SNAPSHOT_DIR, SNAPSHOT_BASENAME, LB_USER, LB_PASSWORD

stages:
  deploy:
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs:
          url: "${DB_URL}"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          snapshotFormat: "JSON"
          outputFile: "${SNAPSHOT}"

      - type: liquibase
        command: update
        cmdArgs:
          changelogFile: "changelog/master.xml"
          url: "${DB_URL}"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          contexts: "${CONTEXTS}"

      - type: liquibase
        command: diff
        cmdArgs:
          # Compare LIVE target vs the PRE snapshot (offline reference)
          url: "${DB_URL}"
          referenceUrl: "offline:postgresql?snapshot=${SNAPSHOT_BASENAME}"
          searchPath: "${SNAPSHOT_DIR}"
          outputFile: "${DIFF}"
