# Minimal flow file controlled by toggles:
#   RUN_AUDIT:    on/off
#   RUN_DRIFT:    on/off
#   RUN_POLICIES: on/off
# Connection comes from liquibase.properties in the repo/workspace.

globalVariables:
  RUN_AUDIT:      "${RUN_AUDIT:-on}"
  RUN_DRIFT:      "${RUN_DRIFT:-on}"
  RUN_POLICIES:   "${RUN_POLICIES:-on}"
  CHANGELOG_FILE: "${CHANGELOG_FILE:-changelog-sql/master.xml}"

stages:
  Default:
    actions:
      # 1) Drift (optional). Non-blocking; remove continueOnError to make it gate the flow.
      - type: liquibase
        if: "RUN_DRIFT == 'on'"
        command: drift
        continueOnError: true

      # 2) Policies / checks (optional)
      - type: liquibase
        if: "RUN_POLICIES == 'on'"
        command: checks run
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"

      # 3) Audits (optional): quick status + snapshot
      - type: liquibase
        if: "RUN_AUDIT == 'on'"
        command: status
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"

      - type: liquibase
        if: "RUN_AUDIT == 'on'"
        command: snapshot

      # 4) (Optional) Deploy — uncomment if you want to include the update
      # - type: liquibase
      #   command: update
      #   cmdArgs:
      #     changelog-file: "${CHANGELOG_FILE}"
