# Minimal flow file that runs/skip steps based on env toggles:
#   RUN_AUDIT:   on/off
#   RUN_DRIFT:   on/off
#   RUN_POLICIES:on/off
# Connection details come from liquibase.properties

globalVariables:
  RUN_AUDIT:    "${RUN_AUDIT:-on}"
  RUN_DRIFT:    "${RUN_DRIFT:-on}"
  RUN_POLICIES: "${RUN_POLICIES:-on}"
  CHANGELOG_FILE: "${CHANGELOG_FILE:-changelog-sql/master.xml}"

stages:
  Default:
    actions:
      # 1) Drift (optional)
      - type: liquibase
        if: "RUN_DRIFT == 'on'"
        command: drift
        # Non-blocking drift; remove this if you want drift failures to stop the flow
        continueOnError: true

      # 2) Policies / checks (optional)
      - type: liquibase
        if: "RUN_POLICIES == 'on'"
        command: checks run
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"

      # 3) Audits (optional): quick status + snapshot
      - type: liquibase
        if: "RUN_AUDIT == 'on'"
        command: status
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"

      - type: liquibase
        if: "RUN_AUDIT == 'on'"
        command: snapshot

      # 4) (Optional) Deploy — uncomment if you want an update as part of this flow
      # - type: liquibase
      #   command: update
      #   cmdArgs:
      #     changelog-file: "${CHANGELOG_FILE}"
