# liquibase.flowfile.yaml
# Toggles: RUN_AUDIT, RUN_DRIFT, RUN_POLICIES -> on/off/true/false/1/0
# Primary DB (target) comes from liquibase.properties (url=username=password there).
# Reference DB for diff comes from TEST_URL + LB_USER/LB_PWD env vars.
# liquibase.flowfile.yaml (only the diff action + new globals shown)

globalVariables:
  RUN_AUDIT:      "${RUN_AUDIT:-on}"
  RUN_DRIFT:      "${RUN_DRIFT:-on}"
  RUN_POLICIES:   "${RUN_POLICIES:-on}"
  CHANGELOG_FILE: "${CHANGELOG_FILE:-changelog/master.xml}"
  TEST_URL:       "${TEST_URL:-}"
  # NEW: separate reference creds, defaulting to LB_* so it works even if you don't set them
  REF_DB_USER:    "${REF_DB_USER:-${LB_USER:-}}"
  REF_DB_PWD:     "${REF_DB_PWD:-${LB_PWD:-}}"

stages:
  Default:
    actions:
      - type: liquibase
        if: "RUN_DRIFT == 'on' || RUN_DRIFT == 'true' || RUN_DRIFT == 'True' || RUN_DRIFT == '1'"
        command: diff
        continueOnError: true
        cmdArgs:
          reference-url:      "${TEST_URL}"
          reference-username: "${REF_DB_USER}"
          reference-password: "${REF_DB_PWD}"
          # target side: still uses liquibase.properties, but we also pass creds explicitly
          username:           "${LB_USER}"
          password:           "${LB_PWD}"

      - type: liquibase
        if: "RUN_POLICIES == 'on' || RUN_POLICIES == 'true' || RUN_POLICIES == 'True' || RUN_POLICIES == '1'"
        command: checks run
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"

      - type: liquibase
        if: "RUN_AUDIT == 'on' || RUN_AUDIT == 'true' || RUN_AUDIT == 'True' || RUN_AUDIT == '1'"
        command: status
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"

      - type: liquibase
        if: "RUN_AUDIT == 'on' || RUN_AUDIT == 'true' || RUN_AUDIT == 'True' || RUN_AUDIT == '1'"
        command: snapshot
