# liquibase.flowfile.yaml
# Toggles: RUN_AUDIT, RUN_DRIFT, RUN_POLICIES -> on/off/true/false/1/0
# Primary DB (target) comes from liquibase.properties (url=username=password there).
# Reference DB for diff comes from TEST_URL + LB_USER/LB_PWD env vars.

globalVariables:
  RUN_AUDIT:      "${RUN_AUDIT:-on}"
  RUN_DRIFT:      "${RUN_DRIFT:-on}"
  RUN_POLICIES:   "${RUN_POLICIES:-on}"
  CHANGELOG_FILE: "${CHANGELOG_FILE:-changelog/master.xml}"
  TEST_URL:       "${TEST_URL:-}"
  LB_USER:        "${LB_USER:-}"
  LB_PWD:         "${LB_PWD:-}"

stages:
  Default:
    actions:
      # 1) DIFF (optional). Non-blocking; remove continueOnError to make it gate the flow.
      - type: liquibase
        if: "RUN_DRIFT == 'on' || RUN_DRIFT == 'true' || RUN_DRIFT == 'True' || RUN_DRIFT == '1'"
        command: diff
        continueOnError: true
        cmdArgs:
          reference-url:      "${TEST_URL}"
          reference-username: "${LB_USER}"
          reference-password: "${LB_PWD}"
          # main (target) side comes from liquibase.properties, but we also pass creds explicitly:
          username:           "${LB_USER}"
          password:           "${LB_PWD}"

      # 2) POLICIES (optional)
      - type: liquibase
        if: "RUN_POLICIES == 'on' || RUN_POLICIES == 'true' || RUN_POLICIES == 'True' || RUN_POLICIES == '1'"
        command: checks run
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"

      # 3) AUDITS (optional): status + snapshot
      - type: liquibase
        if: "RUN_AUDIT == 'on' || RUN_AUDIT == 'true' || RUN_AUDIT == 'True' || RUN_AUDIT == '1'"
        command: status
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"

      - type: liquibase
        if: "RUN_AUDIT == 'on' || RUN_AUDIT == 'true' || RUN_AUDIT == 'True' || RUN_AUDIT == '1'"
        command: snapshot
