# Flow: snapshot → update → diff (reference = pre-snapshot via offline URL)
# Values come from env: DB_URL, CONTEXTS, SNAPSHOT, DIFF, LB_USER, LB_PASSWORD

stages:
  deploy:
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs:
          url: "${DB_URL}"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          snapshotFormat: "JSON"
          outputFile: "${SNAPSHOT}"

      - type: liquibase
        command: update
        cmdArgs:
          changelogFile: "changelog/master.xml"
          url: "${DB_URL}"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          contexts: "${CONTEXTS}"

      - type: liquibase
        command: diff
        cmdArgs:
          # LIVE target vs PRE snapshot (as offline reference)
          url: "${DB_URL}"
          referenceUrl: "offline:postgresql?snapshot=${SNAPSHOT}"
          outputFile: "${DIFF}"
