# Runs: policies (checks) → simple snapshot → update → diff (dev → test)
# Expects env vars: LB_URL, DEV_URL, TEST_URL, LB_USER, LB_PWD
# Optional: CHANGELOG_FILE (defaults to changelog/master.xml)

globalVariables:
  CHANGELOG_FILE: "${CHANGELOG_FILE:-changelog/master.xml}"

stages:
  Default:
    actions:
      - type: liquibase
        command: checks run
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"
          url: "${LB_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"

      - type: liquibase
        command: snapshot
        cmdArgs:
          url: "${LB_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"

      - type: liquibase
        command: update
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"
          url: "${LB_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"

      - type: liquibase
        command: diff
        cmdArgs:
          reference-url: "${DEV_URL}"
          reference-username: "${LB_USER}"
          reference-password: "${LB_PWD}"
          url: "${TEST_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"
