# Flow: snapshot → update → diff (reference = pre-snapshot via offline URL)
# Env vars provided by the workflow/local shell:
#   DB_URL, CONTEXTS, SNAPSHOT, DIFF, LB_USER, LB_PASSWORD

stages:
  deploy:
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs:
          url: "${DB_URL}"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          snapshot-format: "JSON"
          output-file: "${SNAPSHOT}"

      - type: liquibase
        command: update
        cmdArgs:
          changelog-file: "changelog/master.xml"
          url: "${DB_URL}"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          contexts: "${CONTEXTS}"

      - type: liquibase
        command: diff
        cmdArgs:
          # Compare live DB (url) to the pre-run snapshot (reference-url via offline snapshot)
          url: "${DB_URL}"
          reference-url: "offline:snapshot?snapshot=${SNAPSHOT}"
          output-file: "${DIFF}"
