# Expects env: LB_URL, DEV_URL, TEST_URL, LB_USER, LB_PWD
# Toggles: RUN_POLICIES=on|off, RUN_SNAPSHOT=on|off
# Optional: CHANGELOG_FILE (defaults below)

globalVariables:
  CHANGELOG_FILE: "${CHANGELOG_FILE:-changelog/master.xml}"
  RUN_POLICIES:   "${RUN_POLICIES:-on}"
  RUN_SNAPSHOT:   "${RUN_SNAPSHOT:-on}"

stages:
  Default:
    actions:
      # policies (checks) — only if RUN_POLICIES == on
      - type: liquibase
        if: "RUN_POLICIES == 'on'"
        command: checks run
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"
          url: "${LB_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"

      # snapshot (basic) — only if RUN_SNAPSHOT == on
      - type: liquibase
        if: "RUN_SNAPSHOT == 'on'"
        command: snapshot
        cmdArgs:
          url: "${LB_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"

      # update (always runs)
      - type: liquibase
        command: update
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"
          url: "${LB_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"

      # diff dev -> test (always runs)
      - type: liquibase
        command: diff
        cmdArgs:
          reference-url: "${DEV_URL}"
          reference-username: "${LB_USER}"
          reference-password: "${LB_PWD}"
          url: "${TEST_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"
