# Flow controlled by:
#   RUN_AUDIT, RUN_DRIFT, RUN_POLICIES  -> on/off/true/false/1/0 supported
# Connection comes from liquibase.properties.

globalVariables:
  RUN_AUDIT:      "${RUN_AUDIT:-on}"
  RUN_DRIFT:      "${RUN_DRIFT:-on}"
  RUN_POLICIES:   "${RUN_POLICIES:-on}"
  CHANGELOG_FILE: "${CHANGELOG_FILE:-changelog/master.xml}"

stages:
  Default:
    actions:
      # Drift (optional, non-blocking so it never halts the rest)
      - type: liquibase
        if: "RUN_DRIFT == 'on' || RUN_DRIFT == 'true' || RUN_DRIFT == 'True' || RUN_DRIFT == '1'"
        command: drift
        continueOnError: true

      # Policies (optional)
      - type: liquibase
        if: "RUN_POLICIES == 'on' || RUN_POLICIES == 'true' || RUN_POLICIES == 'True' || RUN_POLICIES == '1'"
        command: checks run
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"

      # Audits (optional): status + snapshot
      - type: liquibase
        if: "RUN_AUDIT == 'on' || RUN_AUDIT == 'true' || RUN_AUDIT == 'True' || RUN_AUDIT == '1'"
        command: status
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"

      - type: liquibase
        if: "RUN_AUDIT == 'on' || RUN_AUDIT == 'true' || RUN_AUDIT == 'True' || RUN_AUDIT == '1'"
        command: snapshot
