# Flow: snapshot → update → diff (reference = pre-snapshot via offline URL)
# Values come from env: DB_URL, CONTEXTS, SNAPSHOT, DIFF, LB_USER, LB_PASSWORD

stages:
  deploy:
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs:
          url: "${DB_URL}"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          snapshotFormat: "JSON"
          outputFile: "${SNAPSHOT}"

      - type: liquibase
        command: update
        cmdArgs:
          changelogFile: "changelog/master.xml"
          url: "${DB_URL}"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          contexts: "${CONTEXTS}"

      - type: liquibase
        command: diff
        cmdArgs:
          # Compare live DB to the pre-run snapshot via the offline snapshot driver
          url: "${DB_URL}"
          referenceUrl: "offline:snapshot?snapshot=${SNAPSHOT}"
          outputFile: "${DIFF}"
