# Simple Flow: snapshot → (optional) checks → update → post-diff
# Variables TARGET (dev|test|prod), POLICIES (on|off), RUN_ID (freeform)

globalVariables:
  CHANGELOG: "changelog/master.xml"

  # Caller provided; defaults for local runs:
  TARGET:   "${TARGET:-dev}"       # dev | test | prod
  POLICIES: "${POLICIES:-off}"     # on  | off
  RUN_ID:   "${RUN_ID:-manual}"    # used to name files (e.g., GH run id)

  # File names (no directories required)
  SNAPSHOT: "snapshot-${TARGET}-${RUN_ID}.json"
  DIFFOUT:  "diff-${TARGET}-${RUN_ID}.txt"

stages:
  deploy:
    actions:
      # --------- Pre: Snapshot (always) ----------
      - type: liquibase
        if: "${TARGET} == 'dev'"
        command: snapshot
        cmdArgs:
          changelog-file: "${CHANGELOG}"
          url: "jdbc:postgresql://localhost:5433/postgres"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          snapshotFormat: "JSON"
          outputFile: "${SNAPSHOT}"

      - type: liquibase
        if: "${TARGET} == 'test'"
        command: snapshot
        cmdArgs:
          changelog-file: "${CHANGELOG}"
          url: "jdbc:postgresql://localhost:5434/postgres"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          snapshotFormat: "JSON"
          outputFile: "${SNAPSHOT}"

      - type: liquibase
        if: "${TARGET} == 'prod'"
        command: snapshot
        cmdArgs:
          changelog-file: "${CHANGELOG}"
          url: "jdbc:postgresql://localhost:5435/postgres"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          snapshotFormat: "JSON"
          outputFile: "${SNAPSHOT}"

      # --------- Optional: policies/checks (pre-update) ----------
      - type: liquibase
        if: "${POLICIES} == 'on'"
        command: checks run
         cmdArgs: {checks-scope: "changelog"} 

      # --------- Update (per env with contexts) ----------
      - type: liquibase
        if: "${TARGET} == 'dev'"
        command: update
        cmdArgs:
          changelog-file: "${CHANGELOG}"
          url: "jdbc:postgresql://localhost:5433/postgres"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          contexts: "dev,dev,test,prod"

      - type: liquibase
        if: "${TARGET} == 'test'"
        command: update
        cmdArgs:
          changelog-file: "${CHANGELOG}"
          url: "jdbc:postgresql://localhost:5434/postgres"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          contexts: "test,dev,test,prod"

      - type: liquibase
        if: "${TARGET} == 'prod'"
        command: update
        cmdArgs:
          changelog-file: "${CHANGELOG}"
          url: "jdbc:postgresql://localhost:5435/postgres"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          contexts: "prod,dev,test,prod"

      # --------- Post: Diff live vs pre-snapshot ----------
      - type: liquibase
        command: diff
        cmdArgs:
          referenceSnapshot: "${SNAPSHOT}"
          # url matches the chosen env (reuse branch-specific URL):
          url: "${TARGET == 'dev'  ? 'jdbc:postgresql://localhost:5433/postgres' :
                TARGET == 'test' ? 'jdbc:postgresql://localhost:5434/postgres' :
                                    'jdbc:postgresql://localhost:5435/postgres'}"
          username: "${LB_USER}"
          password: "${LB_PASSWORD}"
          outputFile: "${DIFFOUT}"
