# Flow toggles come from env:
#   RUN_AUDIT, RUN_DRIFT, RUN_POLICIES -> on/off
# Connections come from env:
#   Target:   LB_URL, LB_USER, LB_PASSWORD
#   Reference (diff): TEST_URL (uses same LB_USER/LB_PASSWORD)

globalVariables:
  RUN_AUDIT:      "${RUN_AUDIT:-on}"
  RUN_DRIFT:      "${RUN_DRIFT:-on}"
  RUN_POLICIES:   "${RUN_POLICIES:-on}"
  CHANGELOG_FILE: "${CHANGELOG_FILE:-changelog/master.xml}"

  LB_URL:       "${LB_URL:-}"
  LB_USER:      "${LB_USER:-}"
  LB_PASSWORD:  "${LB_PASSWORD:-}"
  TEST_URL:     "${TEST_URL:-}"

stages:
  Default:
    actions:
      # 1) DIFF (optional). Non-blocking; delete continueOnError to gate the flow.
      - type: liquibase
        if: "RUN_DRIFT == 'on'"
        command: diff
        continueOnError: true
        cmdArgs:
          url:                  "${LB_URL}"
          username:             "${LB_USER}"
          password:             "${LB_PASSWORD}"
          reference-url:        "${TEST_URL}"
          reference-username:   "${LB_USER}"
          reference-password:   "${LB_PASSWORD}"

      # 2) POLICIES (optional)
      - type: liquibase
        if: "RUN_POLICIES == 'on'"
        command: checks run
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"
          url:            "${LB_URL}"
          username:       "${LB_USER}"
          password:       "${LB_PASSWORD}"

      # 3) AUDITS (optional): status + snapshot
      - type: liquibase
        if: "RUN_AUDIT == 'on'"
        command: status
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"
          url:            "${LB_URL}"
          username:       "${LB_USER}"
          password:       "${LB_PASSWORD}"

      - type: liquibase
        if: "RUN_AUDIT == 'on'"
        command: snapshot
        cmdArgs:
          url:            "${LB_URL}"
          username:       "${LB_USER}"
          password:       "${LB_PASSWORD}"
