# Runs: (optionally) checks → snapshot → update → diff(dev→test)
# Expects env: LB_URL, DEV_URL, TEST_URL, LB_USER, LB_PWD
# Optional: CHANGELOG_FILE, RUN_POLICIES

globalVariables:
  CHANGELOG_FILE: "${CHANGELOG_FILE:-changelog/master.xml}"
  RUN_POLICIES:   "${RUN_POLICIES:-on}"   # 'on' or 'off'
  RUN_SNAPSHOT:   "${RUN_SNAPSHOT:-on}"   # 'on' or 'off'

stages:
  Default:
    actions:
      - type: liquibase
        if: "RUN_POLICIES == 'on'"
        command: checks run
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"
          url: "${LB_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"

      - type: liquibase
        if: "RUN_SNAPSHOT == 'on'"
        command: snapshot
        cmdArgs:
          url: "${LB_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"

      - type: liquibase
        command: update
        cmdArgs:
          changelog-file: "${CHANGELOG_FILE}"
          url: "${LB_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"

      - type: liquibase
        command: diff
        cmdArgs:
          reference-url: "${DEV_URL}"
          reference-username: "${LB_USER}"
          reference-password: "${LB_PWD}"
          url: "${TEST_URL}"
          username: "${LB_USER}"
          password: "${LB_PWD}"
